### ISSUE TITLE
Watch doesn't support near-file-operation?

### ISSUE THREAD

**Issue by bzbetty** [danielwaltz/vite-plugin-graphql-codegen#12]
**graphql.config.yml**
```
schema: ./schema.graphql
generates:  
  app/common/graphql/types.ts:
    plugins:
      - typescript
      - typescript-validation-schema
    config:
      onlyOperationTypes: true
      useTypeImports: false
      exposeFetcher: false     
      strictScalars: true
      schema: yup  
  app/:
    documents: "app/**/*.graphql"
    preset: near-operation-file
    presetConfig:
        extension: .generated.ts
        baseTypesPath: "~@types"
    plugins:      
      - "typescript-operations"
      - "typescript-react-query"
    config:            
      legacyMode: false
      fetcher: "@httpClient#httpClient"  
```
    
when using watch it doesn't seem to pickup on 'documents: "app/**/*.graphql"' that's nested under app/:

if I move it up to the top level under schema it starts detecting changes but the graphql doesn't generate how I wanted.
