### ISSUE TITLE
graphql document matcher compares absolute and relative paths

### ISSUE THREAD

**Issue by KholdStare** [danielwaltz/vite-plugin-graphql-codegen#23]
Hi, I tried using this plugin, but ran into an issue where the watch functionality didn't work.

I put a few log statements and enabled debug mode in the plugin, and found this:

```
VITE PLUGIN GRAPHQL CODEGEN   File changed: /home/kholdstare/workspace/code/frontend/operations.graphql 
VITE PLUGIN GRAPHQL CODEGEN   {
  'src/generated/subgraph.ts': {
    documents: [ 'operations.graphql' ],
    plugins: [ 'typescript', 'typescript-operations', 'typescript-urql' ],
    config: {
      useTypeImports: true,
      strictScalars: true,
      pureMagicComment: true,
      scalars: [Object]
    },
    hooks: { afterOneFileWrite: [Array] }
  }
}
VITE PLUGIN GRAPHQL CODEGEN   Check for document file successful in file watcher 
VITE PLUGIN GRAPHQL CODEGEN   File did not match a graphql document 
VITE PLUGIN GRAPHQL CODEGEN   Check for schema file successful in file watcher 
VITE PLUGIN GRAPHQL CODEGEN   File did not match a graphql schema 
```

If you look, the "file changed" is an absolute path, while the document filepath in the config is a relative path. Perhaps `resolve` should be called on the `documents` paths?

This fails:
https://github.com/danielwaltz/vite-plugin-graphql-codegen/blob/main/src/utils/fileMatchers.ts#L21

**Comment by danielwaltz** [comment]
Good catch. Will look into this soon!

**Comment by danielwaltz** [comment]
@KholdStare Let me know if this fixes it for you! 🤞

**Comment by KholdStare** [comment]
Hi @danielwaltz , I may have spoken too soon about what was the issue. After some more debugging, I discovered that I was using a graphql config like this:

```yaml
schema:
  - ../blockchain/subgraph/remote-schema.graphql
generates:
  "src/generated/subgraph.ts":
    documents:
      - operations.graphql
    plugins:
      # see https://the-guild.dev/graphql/codegen/plugins/typescript/typescript
      - typescript
      # see https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations
      - typescript-operations
      # see https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-urql
      - typescript-urql
    config:
      useTypeImports: true # use `import type {}`
      strictScalars: true # make sure all scalars have typescript types
      pureMagicComment: true # helps with treeshaking for bundlers like webpack to reduce bundle size
      scalars: # define typescript types for custom scalars
        Bytes: string
        BigDecimal: string
        BigInt: string
        Int8: number
    hooks:
      afterOneFileWrite:
        - prettier --write
```

In particular the `documents` section was under the `generates` section. That is a valid config, and the `documents` field wasn't being picked up. When I moved `documents` to the top level, everything worked as intended. I don't know if you want to expand support for that (documents inside of generates)
