### ISSUE TITLE
Support `documents` under `generates` field in graphql config

### ISSUE THREAD

**Issue by KholdStare** [danielwaltz/vite-plugin-graphql-codegen#24]
Using a config such as the one below fails to find the listed `documents` since it is not at the top level. I think the code should also recursively gather all `documents` fiels from all `generates` sections.

```yaml
schema:
  - ../blockchain/subgraph/remote-schema.graphql
generates:
  "src/generated/subgraph.ts":
    documents:
      - operations.graphql
    plugins:
      # see https://the-guild.dev/graphql/codegen/plugins/typescript/typescript
      - typescript
      # see https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-operations
      - typescript-operations
      # see https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-urql
      - typescript-urql
    config:
      useTypeImports: true # use `import type {}`
      strictScalars: true # make sure all scalars have typescript types
      pureMagicComment: true # helps with treeshaking for bundlers like webpack to reduce bundle size
      scalars: # define typescript types for custom scalars
        Bytes: string
        BigDecimal: string
        BigInt: string
        Int8: number
    hooks:
      afterOneFileWrite:
        - prettier --write
```
