### ISSUE TITLE
Fix monorepo path resolution

### ISSUE THREAD

**Issue by aaronadamsCA** [danielwaltz/vite-plugin-graphql-codegen#37]
I already reported this as an upstream issue: https://github.com/dotansimha/graphql-code-generator/issues/10279

To summarize, if I put this `graphql.config.yaml` at the monorepo root:

```yaml
schema: ./schemas/foo.graphql
documents: ./packages/foo/**/*.graphql
extensions:
  codegen:
    generates:
      ./packages/foo/graphql.ts:
        plugins:
          - typescript
          - typescript-operations
          - typed-document-node
```

And I configure `vite-plugin-graphql-codegen` in a child package:

```ts
export default defineConfig({
  root: import.meta.dirname,
  plugins: [
    codegen(),
  ],
});
```

The root config is automatically found, but its paths are incorrectly resolved relative to the working directory of the child package. They should be resolved relative to the config file.

The main use case for this is multi-project support (#35).

It seems to me this plugin is already doing what it can/should here! But maybe you can think of a way to work around the problem.
